services:
 nginx:
  image: nginx:latest
  container_name: nginx
  restart: always
  extra_hosts:
  - "host.docker.internal:host-gateway"
  ports:
    - "${PORTA_EXTERNA_PHP_5_4:-80}:80" # php 5.4 não terminado
    - "${PORTA_EXTERNA_PHP_5_6:-81}:81" # php 5.6
    - "${PORTA_EXTERNA_PHP_7_4:-82}:82" # php 7.4
  volumes:
  - ${NIVEL_DIR_PROJETO:-../}:/var/www/html
  - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  links:
  - php54
  - php56
  - php74
  - vite
  # - db_mysql # mysql (Esta funcionando, mas não está sendo usado. Ao conectar no mysql, use o host: db_mysql ao invés de localhost)
 php54:
  image: php:5.4-fpm
  restart: always
  volumes:
  - ${NIVEL_DIR_PROJETO:-../}:/var/www/html
  - ./docker/php/80-php_global.ini:/usr/local/etc/php/conf.d/80-php_global.ini
 php56:
  build: 
    context: .
    dockerfile: ./docker/php/php56/Dockerfile.php56
  container_name: php56-fpm
  restart: always
  volumes:
  - ${NIVEL_DIR_PROJETO:-../}:/var/www/html
  - ./docker/php/80-php_global.ini:/etc/php/5.6/fpm/conf.d/80-php_global.ini
  - ./docker/php/php56/20-xdebug.ini:/etc/php/5.6/fpm/conf.d/20-xdebug.ini
 php74:
  build: 
    context: .
    dockerfile: ./docker/php/php74/Dockerfile.php74
  container_name: php74-fpm
  restart: always
  volumes:
  - ${NIVEL_DIR_PROJETO:-../}:/var/www/html
  - ./docker/php/80-php_global.ini:/etc/php/7.4/fpm/conf.d/80-php_global.ini
  - ./docker/php/php74/20-xdebug.ini:/etc/php/7.4/fpm/conf.d/20-xdebug.ini
 vite:
  build: 
    context: .
    dockerfile: ./docker/vite/Dockerfile.vite
  container_name: vite
  ports:
    - "${PORTA_EXTERNA_VITE:-5173}:5173"
  restart: always
  volumes:
  - ${NIVEL_DIR_PROJETO:-../}:/var/www/html
  working_dir: ${CAMINHO_DIR_VITE:-/var/www/html/vue}
  command: "sh -c 'npm install && npm run dev'"

# Comentei o mysql, pois não está sendo usado. Mas caso queira usar, descomente aqui e no link do nginx
#  db_mysql:
#   image: mysql:5.7
#   container_name: mysql
#   ports:
#   - "3306:3306"
#   volumes:
#     - ./docker/mysql/data:/var/lib/mysql/
#   command: --default-authentication-plugin=mysql_native_password
#   restart: always
#   environment:
#     MYSQL_ROOT_PASSWORD: root
#     MYSQL_DATABASE: db_teste