services:
 nginx:
  image: nginx:latest
  container_name: nginx
  restart: always
  extra_hosts:
  - "host.docker.internal:host-gateway"
  ports:
    - "${PORTA_EXTERNA_PHP_5_6:-80}:80" # php 5.6
    - "${PORTA_EXTERNA_PHP_7_4:-81}:81" # php 7.4
  volumes:
  - ${NIVEL_DIR_PROJETO:-../}:/var/www/html
  - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  links:
  - php56
  - php74
  # - vite
  # - db_mysql # mysql (Ao conectar no mysql, use o host: db_mysql ao invés de localhost)
 php56:
  build: 
    context: .
    dockerfile: ./docker/php/php56/Dockerfile.php56
  container_name: php56-fpm
  restart: always
  volumes:
  - ${NIVEL_DIR_PROJETO:-../}:/var/www/html
  - ./docker/php/80-php_global.ini:/etc/php/5.6/fpm/conf.d/80-php_global.ini
  - ./docker/php/php56/20-xdebug.ini:/etc/php/5.6/fpm/conf.d/20-xdebug.ini
 php74:
  build: 
    context: .
    dockerfile: ./docker/php/php74/Dockerfile.php74
  container_name: php74-fpm
  restart: always
  volumes:
  - ${NIVEL_DIR_PROJETO:-../}:/var/www/html
  - ./docker/php/80-php_global.ini:/etc/php/7.4/fpm/conf.d/80-php_global.ini
  - ./docker/php/php74/20-xdebug.ini:/etc/php/7.4/fpm/conf.d/20-xdebug.ini
 ngrok:
    image: wernight/ngrok
    container_name: ngrok
    restart: always
    ports:
      - "4040:4040"
    env_file: .env
    environment:
      NGROK_PORT: nginx:80
#  vite:
#   build: 
#     context: .
#     dockerfile: ./docker/vite/Dockerfile.vite
#   container_name: vite
#   ports:
#     - "${PORTA_EXTERNA_VITE:-5173}:5173"
#   restart: always
#   volumes:
#   - ${NIVEL_DIR_PROJETO:-../}:/var/www/html
#   working_dir: ${CAMINHO_DIR_VITE:-/var/www/html/vue}
#   command: "sh -c 'npm install && npm run dev'"

#  db_mysql:
#   image: mysql:5.7
#   container_name: mysql
#   ports:
#   - "3311:3306"
#   volumes:
#     - ./docker/mysql/data:/var/lib/mysql/
#     - ./docker/mysql/restore_db:/docker-entrypoint-initdb.d/
#   command: --default-authentication-plugin=mysql_native_password
#   restart: always
#   environment:
#     MYSQL_ROOT_PASSWORD: root