version: '3.8'

services:
  php:
    container_name: viteinprojectexist-php74
    build: .
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
    - "86:80"
    - "5174:5173"
    volumes:
    - ../:/var/www/html
    - /var/www/html
    