services:
 nginx:
  build: 
    context: .
    dockerfile: nginx/Dockerfile.nginx
  container_name: nginx
  restart: always
  extra_hosts:
  - "host.docker.internal:host-gateway"
  ports:
    - "80:80" # php 5.4 não terminado
    - "81:81" # php 5.6
    - "82:82" # php 7.4
    - "5173:5173" # vite
  volumes:
  - ../:/var/www/html
  - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  links:
  - php54
  - php56
  - php74
  # - db_mysql # mysql (Esta funcionando, mas não está sendo usado. Ao conectar no mysql, use o host: db_mysql ao invés de localhost)
 php54:
  image: php:5.4-fpm
  container_name: php54-fpm
  restart: always
  volumes:
  - ../:/var/www/html
  - ./php/80-php_global.ini:/usr/local/etc/php/conf.d/80-php_global.ini
 php56:
  build: 
    context: .
    dockerfile: php/php56/Dockerfile.php56
  container_name: php56-fpm
  restart: always
  volumes:
  - ../:/var/www/html
  - ./php/80-php_global.ini:/etc/php/5.6/fpm/conf.d/80-php_global.ini
  - ./php/php56/20-xdebug.ini:/etc/php/5.6/fpm/conf.d/20-xdebug.ini
 php74:
  build: 
    context: .
    dockerfile: php/php74/Dockerfile.php74
  container_name: php74-fpm
  restart: always
  volumes:
  - ../:/var/www/html
  - ./php/80-php_global.ini:/etc/php/7.4/fpm/conf.d/80-php_global.ini
  - ./php/php74/20-xdebug.ini:/etc/php/7.4/fpm/conf.d/20-xdebug.ini
# Comentei o mysql, pois não está sendo usado. Mas caso queira usar, descomente aqui e no link do nginx
#  db_mysql:
#   image: mysql:5.7
#   container_name: mysql
#   ports:
#   - "3306:3306"
#   command: --default-authentication-plugin=mysql_native_password
#   restart: always
#   environment:
#     MYSQL_ROOT_PASSWORD: root
#     MYSQL_DATABASE: teste