version: '3.8'

services:
  nginx:
    container_name: php56_php74_nginx
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
    - "80:80" # default index.html (none php)
    - "81:81" # php56
    - "82:82" # php74
    - "5173:5173" # vite
    volumes:
    - ../:/var/www/html
    - /var/www/html
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
    depends_on:
    - php
    
  php:
    container_name: php56_php74_php
    build:
      context: .
      dockerfile: Dockerfile_php
    volumes:
    - ../:/var/www/html
    - /var/www/html
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"