# Imagem base
FROM ubuntu:20.04

WORKDIR /var/www/html

# Atualização do sistema e instalação das dependências
RUN apt-get update && apt-get install -y nginx nano curl

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g npm@9.6.2

# # Copia as configurações do Nginx para os sites disponíveis
# RUN rm /etc/nginx/sites-available/default
COPY nginx/site-php56.conf /etc/nginx/sites-available/php56
COPY nginx/site-php74.conf /etc/nginx/sites-available/php74

# # Cria um link simbólico dos sites disponíveis para os sites ativos
RUN ln -s /etc/nginx/sites-available/php56 /etc/nginx/sites-enabled/
RUN ln -s /etc/nginx/sites-available/php74 /etc/nginx/sites-enabled/

# # Copia a configuração do Nginx
# POSTERIORMENTE SERÁ FEITO. AINDA NÃO ESTÁ FUNCIONANDO
# COPY nginx/nginx.conf /etc/nginx/nginx.conf

# # Dando permissão global para o usuário www-data
RUN usermod -u 1000 www-data
RUN chown -R www-data:www-data /var/www/html

# # Inicia o Nginx
CMD service nginx start && tail -f /dev/null