# Imagem base
FROM ubuntu:20.04

WORKDIR /var/www/html

# Atualização do sistema e instalação das dependências
RUN apt-get update && apt-get install -y nano curl

# Adiciona o repositório do PHP
RUN apt-get install -y software-properties-common && \
    add-apt-repository ppa:ondrej/php -y && \
    apt-get update

# Instalação do PHP 7.4
RUN apt-get -y install php7.4-fpm php7.4-cli php7.4-mysql php7.4-curl \
    php7.4-json php7.4-interbase php7.4-xml php7.4-mbstring php7.4-zip \
    php7.4-gd php7.4-xdebug php7.4-redis php7.4-imagick 

# # Instalação do PHP 5.6
RUN apt-get -y install php5.6-fpm php5.6-cli php5.6-mysql php5.6-curl \
    php5.6-json php5.6-interbase php5.6-xml php5.6-mbstring php5.6-zip \
    php5.6-gd php5.6-xdebug php5.6-redis php5.6-imagick 

# # Copia as configurações do PHP-FPM
COPY php/99-php_global.ini /etc/php/7.4/fpm/conf.d/98.ini
COPY php/99-php_global.ini /etc/php/5.6/fpm/conf.d/98.ini

COPY php/php56/99-php56.ini /etc/php/5.6/fpm/conf.d/99.ini
COPY php/php74/99-php74.ini /etc/php/7.4/fpm/conf.d/99.ini

COPY --from=composer:2.2 /usr/bin/composer /usr/bin/composer

# # Dando permissão global para o usuário www-data
RUN usermod -u 1000 www-data
RUN chown -R www-data:www-data /var/www/html

# # Inicia o PHP-FPM
CMD service php5.6-fpm start && service php7.4-fpm start && tail -f /dev/null