FROM php:5.6-apache

# Igual nas duas versões (Ao alterar, alterar no 7.4 também)

    WORKDIR /var/www/html

    RUN apt-get update && \
        apt-get upgrade -y && \
        apt-get -y install firebird-dev nano tzdata libzip-dev libicu-dev perl

    RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
        apt-get install -y nodejs && \
        npm install -g npm@9.6.2

    ENV TZ=America/Sao_Paulo
    ENV LD_LIBRARY_PATH /usr/lib/x86_64-linux-gnu

    COPY docker/php/plus_php.ini ${PHP_INI_DIR}/conf.d/plus_php.ini

    COPY --from=composer:2.2 /usr/bin/composer /usr/bin/composer

# Ate aqui igual nas duas versões


RUN docker-php-ext-install interbase zip intl

COPY docker/php/xdebug/xdebug-2.5.5.tgz /tmp/
RUN cd /tmp && \
    tar xvzf xdebug-2.5.5.tgz && \
    cd xdebug-2.5.5 && \
    phpize && \
    ./configure && \
    make && \
    cp modules/xdebug.so $(php-config --extension-dir) && \
    echo "zend_extension=$(php-config --extension-dir)/xdebug.so" > /usr/local/etc/php/conf.d/xdebug.ini && \
    rm -rf /tmp/xdebug*

# COPY start.sh /usr/local/bin/
# RUN chmod +x /usr/local/bin/start.sh

# CMD ["/usr/local/bin/start.sh"]

# Na primeira vez que rodar se der erro, rodar novamente o comando "docker compose up -d --build". porem descomentando a linha abaixo. Depois de rodar uma vez, comentar novamente (não faço ideia do motivo, mas funciona)

# RUN a2enmod rewrite
# RUN service apache2 restart