version: '3.8'

services:
  php:
    container_name: viteinprojectexist-php56
    build: .
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
    - "85:80"
    - "5173:5173"
    volumes:
    - ../:/var/www/html
    - /var/www/html
    